name: HotbarManager
version: '${project.version}'
main: me.kiiya.hotbarmanager.HotbarManager
softdepend: [ PlaceholderAPI, BedWars1058, BedWars2023, BedWarsProxy, BWProxy2023, BedWars1058-Compass ]
api-version: '1.13'
commands:
  hbm:
    aliases: [ hbmanager, hotbarmanager ]
    description: Hotbar Manager gui command
    permission: hotbarmanager.menu